import NavBar from "./components/NavBar/NavBar";
export const metadata = {
  title: 'app-mail',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({ children, }: { children: React.ReactNode }) {

  return (
    <>
      <NavBar />
      {children}
    </>

  )
}
